spring:  
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
    consul:
      routes:
        - id: usuarios-service
          uri: lb://usuarios-service
          predicates:
            - Path=/usuarios/**
          filters:
            - RewritePath=/usuarios/(?<path>.*), /$\{path}
        - id: pedidos-service
          uri: lb://pedidos-service
          predicates:
            - Path=/pedidos/**
          filters:
            - RewritePath=/pedidos/(?<path>.*), /$\{path}
        - id: cuentas-service
          uri: lb://cuentas-service
          predicates:
            - Path=/cuentas/**
          filters:
            - RewritePath=/cuentas/(?<path>.*), /$\{path}
        - id: productos-service
          uri: lb://producto-service
          predicates:
            - Path=/producto/**
          filters:
            - RewritePath=/producto/(?<path>.*), /$\{path}


logging.level.com.netflix: DEBUG
